name: Deploy PAM

on:
  push:
    branches: [ master ]
    paths:
      - 'LandingPage/**'
      - 'JavaScript-Playground/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Checkout LandingPage
      uses: actions/checkout@v3
      with:
        repository: a81Biz/LandingPage
        path: LandingPage
        ref: master

    - name: Checkout JavaScript-Playground
      uses: actions/checkout@v3
      with:
        repository: a81Biz/JavaScript-Playground
        path: JavaScript-Playground
        ref: main

    - name: Install dependencies
      run: npm install gh-pages --save-dev
      run: npm install
    - name: Build
      run: npm run deploy

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        github_token: ${{ secrets.PAM_TOKEN }}
        branch: gh-pages
        folder: build 