name: Deploy PAM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout LandingPage
      uses: actions/checkout@v3
      with:
        repository: a81Biz/LandingPage
        path: LandingPage
        ref: master

    - name: Checkout JavaScript-Playground
      uses: actions/checkout@v3
      with:
        repository: a81Biz/JavaScript-Playground
        path: JavaScript-Playground
        ref: main

    # Copiar los archivos HTML y JS al directorio de despliegue
    - name: Copy LandingPage Content
      run: |
        mkdir -p build/LandingPage
        cp -R LandingPage/* build/LandingPage/
        ls build/LandingPage  # Verificar que los archivos se copian correctamente

    - name: Copy JavaScript-Playground Content
      run: |
        mkdir -p build/JavaScript-Playground
        cp -R JavaScript-Playground/* build/JavaScript-Playground/
        ls build/JavaScript-Playground  # Verificar que los archivos se copian correctamente

    # Verificación del contenido antes del despliegue
    - name: Verify Build Content
      run: ls -R build  # Lista todo el contenido de la carpeta build antes del despliegue

    # Añadir un archivo .nojekyll para evitar problemas con GitHub Pages
    - name: Add .nojekyll file
      run: echo "" > build/.nojekyll

    # Configuración de Git para el despliegue
    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Desplegar a GitHub Pages asegurando que todos los archivos están correctamente copiados
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        github_token: ${{ secrets.PAM_TOKEN }}
        branch: gh-pages
        folder: build
        debug: true  # Activar depuración para más detalles