name: Deploy PAM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout LandingPage
      uses: actions/checkout@v3
      with:
        repository: a81Biz/LandingPage
        path: LandingPage
        ref: master

    - name: Checkout JavaScript-Playground
      uses: actions/checkout@v3
      with:
        repository: a81Biz/JavaScript-Playground
        path: JavaScript-Playground
        ref: main

    - name: Copy LandingPage Content
      run: |
        mkdir -p build/LandingPage
        cp -R LandingPage/* build/LandingPage/
        ls build/LandingPage

    - name: Copy JavaScript-Playground Content
      run: |
        mkdir -p build/JavaScript-Playground
        cp -R JavaScript-Playground/* build/JavaScript-Playground/
        ls build/JavaScript-Playground

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Check Build Directory
      run: |
        if [ ! -d "build" ]; then
          echo "Error: Build directory not found."
          exit 1
        fi

    - name: Add .nojekyll file
      run: echo "" > build/.nojekyll

    # Configuración de Git para evitar errores de identidad
    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        github_token: ${{ secrets.PAM_TOKEN }}
        branch: gh-pages
        folder: build
