name: Deploy PAM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Construir la aplicaci칩n React principal (PAM)
    - name: Install dependencies for PAM
      run: npm install

    - name: Build PAM
      run: npm run build

    # Verificar el contenido de la aplicaci칩n React en la carpeta build
    - name: Verify PAM Build
      run: ls -R build 

    # Checkout del repositorio LandingPage y copiar su contenido en una subcarpeta
    - name: Checkout LandingPage
      uses: actions/checkout@v3
      with:
        repository: a81Biz/LandingPage
        path: LandingPage
        ref: master

    - name: Copy LandingPage Content
      run: |
        mkdir -p build/LandingPage
        cp -R LandingPage/* build/LandingPage/
        ls build/LandingPage

    # Checkout del repositorio JavaScript-Playground y copiar su contenido en una subcarpeta
    - name: Checkout JavaScript-Playground
      uses: actions/checkout@v3
      with:
        repository: a81Biz/JavaScript-Playground
        path: JavaScript-Playground
        ref: main

    - name: Copy JavaScript-Playground Content
      run: |
        mkdir -p build/JavaScript-Playground
        cp -R JavaScript-Playground/* build/JavaScript-Playground/
        ls -R build/JavaScript-Playground 

    # A침adir un archivo .nojekyll para evitar problemas con GitHub Pages
    - name: Add .nojekyll file
      run: echo "" > build/.nojekyll

    # Configuraci칩n de Git para el despliegue
    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Desplegar todo el contenido a GitHub Pages desde la carpeta build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        github_token: ${{ secrets.PAM_TOKEN }}
        branch: gh-pages
        folder: build
        debug: true